version: "3.9"
services:

  result_displayer:
    build:
      context:    .
      dockerfile: Docker
    ports:
      - "8501:8501"
    environment:
      MONGO_URI: "mongodb://mongo:27017"
      RABBITMQ_HOST: "rabbitmq"
      RABBITMQ_PORT: 5672
      RABBITMQ_QUEUE: "feedback_queue"
    depends_on:
      - mongo
      - rabbitmq

  mongo:
    image: mongo
    ports:
      - "27018:27017"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
